server:
  port: 1020



eureka:
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka/
  instance:
    prefer-ip-address: true # 以自己的ip 作为注册访问地址
    instance-id: zuul-server:1020 #在仪表盘显示自己的服务标识



spring:
  application:
    name: zuul-1020

zuul:
  prefix: "/hrm"    # 统一的请求前缀
  ignored-services: "*"
  routes:
    hrm-system: "/system/**"
    hrm-file: "/file/**"
    hrm-course: "/course/**"